services:
  backend:
    build:
      context: ./EasyRent-Back
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: always
    environment:
      - APP_ENV=prod
    volumes:
      - ./EasyRent-Back:/var/www
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    build:
      context: ./EasyRentFront/easyRentFront
      dockerfile: ./Dockerfile
    container_name: react_app
    restart: always
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend

  database:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
